### ISSUE TITLE
Similar Issues Adjustments

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/generate-vector-embeddings#25]
> This issue seems to be similar to the following issue(s):
> 
> * [Do not break the loop when a plugin fails to run](https://github.com/ubiquity-os/ubiquity-os-kernel/issues/120) Similarity: 76.84

This ran extremely fast. 

@sshivaditya2019: 

1. can you make sure that this includes the `www.` prefix so it does not "reference" or "link back" to the similar issue? I'm also curious why it thinks its a similar issue.  
2. Also I think it should probably only check within the same repo, instead of the entire organization. 
3. Rounding the percentage seems useful. It doesn't matter to us below a fraction.
4. Style adjustments:

---

> [!NOTE]
> #### Similar Issues:
>
> - `77%` [Do not break the loop when a plugin fails to run](https://www.github.com/ubiquity-os/ubiquity-os-kernel/issues/120) 

---

_Originally posted by @0x4007 in https://github.com/ubiquity-os/plugins-wishlist/issues/52#issuecomment-2386585263_

**Comment by 0x4007** [comment]
So this should be within repo only, it appears to be network wide which is not very useful.

**Comment by 0x4007** [comment]
> a low match threshold as almost all of them are between 75 to 80.

I think the implementation needs adjustment because in the context of any idea every, perhaps the issues are alike but within the context of a repo they are quite different. Maybe we should use log function.

> Applying a logarithmic function could be useful in this context to adjust the similarity scores, especially if you're trying to emphasize differences at certain ranges. Here's why:
> 
> 1. **Score Distribution**: If most of your similarity scores cluster between 75 and 80, applying a log function could spread out these values more evenly. This makes subtle differences more distinguishable, helping you avoid stacking similar issues that aren't truly alike.
> 
> 2. **Context Sensitivity**: Logarithmic scaling can help distinguish finer details when values are high, which aligns with your concern that issues might be similar in general but differ in specific contexts within the repo.
> 
> You might experiment with different bases (e.g., natural log or log base 10) to see how it impacts your thresholds and similarity evaluation. Applying this transformation before filtering or adjusting the threshold could yield a more nuanced matching process.

**Comment by gentlementlegen** [comment]
So the fact that `/start` didn't respond is due to https://github.com/ubiquity-os/ubiquity-os-kernel/issues/120 however the failure to retrieve pull-requests is unknown, we should have a look.

**Comment by 0x4007** [comment]
@gentlementlegen It is also possible that KV is hitting its limits given all the recent warnings. In this case I guess that the requests would be rate limited `429`

**Comment by gentlementlegen** [comment]
It's a GitHub API request so it is possible that the API got rate limited as well but less likely because we are authenticated as far as I know.

**Comment by 0x4007** [comment]
Had a good [result here](https://github.com/ubiquity-os/plugin-template/issues/25#issuecomment-2388845397) which is aligned with my vision. I am thinking to adjust the UI/UX again.

Let's edit the specification:

```
###### Similar[^01^]
[^01^]: [Near Instant GitHub Actions Cold Boot Times](https://github.com/ubiquity-os/plugin-template/issues/24) 77%
```

Which renders to:

###### Similar[^01^]
[^01^]: [Near Instant GitHub Actions Cold Boot Times](https://github.com/ubiquity-os/plugin-template/issues/24) 77%

**Comment by 0x4007** [comment]
I know, I'm saying that we should actually do it differently. We should append [this](https://github.com/ubiquity-os-marketplace/generate-vector-embeddings/issues/25#issuecomment-2388870939) to the specification because it will look a lot cleaner.

**Comment by 0x4007** [comment]
Ah this still is using the bad conversation rewards algorithm. It would be nice to push the new algorithm to production @gentlementlegen

**Comment by gentlementlegen** [comment]
@0x4007 it seems to use the updated version? What is wrong in it

**Comment by 0x4007** [comment]
https://github.com/ubiquity-os-marketplace/generate-vector-embeddings/issues/25#issuecomment-2388870939 caught my eye as being too high but I'm reviewing the statistics:


```yml
content:
  content: # strange there's content.content
    p:
      score: 0
      elementCount: 3
    a:
      score: 5 # looks like its counting the footnotes as links. I only see three related to the footnotes (these should be hardcoded to be removed.) but there is one unaccounted for that I cant find?
      elementCount: 2
    pre:
      score: 0
      elementCount: 1
    h6:
      score: 1
      elementCount: 1
  result: 11

regex:
  wordCount: 116
  wordValue: 0.2
  result: 11.37
```

I think we have an unaddressed scenario of dealing with footnotes. So we'll need to make a new task then. I also have a feeling that it is counting within the code block, we should not have this. Also its strange to me that it parsed it as `pre` instead of `code` perhaps its because I didn't include the syntax highlighting header?

Regarding config, I think wordCount should probably default to 0.1 including for author, not sure why its 0.2!

1. Ignore links related to footnotes
2. Do not include footnotes in word count credit

**Comment by 0x4007** [comment]
https://github.com/Dicklesworthstone/fast_vector_similarity some interesting algorithms that are relevant @sshivaditya2019
