### ISSUE TITLE
Task Matchmaking

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/generate-vector-embeddings#7]
When a new task is posted to our network, UbiquityOS should recommend qualified contributors. 

- The system must understand the "closed as complete" project specifications. 
- this should run when 
   - an issue is priced, so I believe on `issues.label_added`
   - issue created `issues.created`
   - task specification has been edited `issues.edited `
- if the new task is 75% similar or greater (configurable) it should post a comment with a list of those issues in order of percentage match. This comment SHOULD NOT tag the users. Instead this is intended for a human to check their work, and tag them in as needed. 
- Be sure to add the `www.` prefix on the github href so that it does not register as a "link back" on the GitHub UI over on their issue.  

For example it should look something like:

```
### 0x4007
- ubiquity/ubiquity-dollar#123 87% match. 
### rndquu
- ubiquity/ubiquity-dollar#250 77% match. 
```

- if the search results comment exists, target and edit it instead of reposting. This is relevant when editing the specification. 

Eventually this may be configurable to be network wide (global) organization wide, or repository wide. But for this first version, we will do network wide.

---

Another configuration of this idea could be to recommend the contributor in the organization with the highest match, even if it doesn't hit the threshold. If within the organization, perhaps tagging is appropriate. Perhaps it makes sense to handle this in a separate task.

**Comment by sshivaditya2019** [comment]
@0x4007 So to sum up:

- `Issues` Database, would have the tasks completed. Using assignees we should be able to find who completed the task.
- Then we need to run a similarity search with issues and the new task.

So, to find the who completed the task. Should `assignees` be used or is there a better way to do this ? I think theres a `pull request` field in the payload object.

**Comment by 0x4007** [comment]
First use assignees and fallback to pull author since many organizations are not as strict about assignment. 

The plan is to separately build a scraper basically so when a new person joins our DevPool we can scrape all the public data on their profile to know what types of projects they completed.

**Comment by sshivaditya2019** [comment]
> First use assignees and fallback to pull author since many organizations are not as strict about assignment.
> 
> The plan is to separately build a scraper basically so when a new person joins our DevPool we can scrape all the public data on their profile to know what types of projects they completed.

Is scraper a part of this ticket ? If so, could you add more details about it to the issue spec.
So, we would run a similarity search against the issues. Return the username of the issues.assignees  which most similar (More than 75% threshold) in descending order. Is that right ?

So, right now `issue-dedup` would send a comment if its more than 75% similar. So is it supposed to be in the same comment ? Or Like how is it supposed to work ? Should there be two comments ?

Also, `Another configuration of this idea could be to recommend the contributor in the organization with the highest match, even if it doesn't hit the threshold`. So the 75% threshold is only for task similarity ?

**Comment by 0x4007** [comment]
> > First use assignees and fallback to pull author since many organizations are not as strict about assignment.
> 
> > 
> 
> > The plan is to separately build a scraper basically so when a new person joins our DevPool we can scrape all the public data on their profile to know what types of projects they completed.
> 
> 
> 
> Is scraper a part of this ticket ? If so, could you add more details about it to the issue spec.
> 

Different project. Can make the spec later. I imagine we could ask them to install UbiquityOS and then we can read all the issues from their private repositories. 

> So, we would run a similarity search against the issues. Return the username of the issues.assignees  which most similar (More than 75% threshold) in descending order. Is that right ?
> 
> 

Yes

> 
> So, right now `issue-dedup` would send a comment if its more than 75% similar. So is it supposed to be in the same comment ? Or Like how is it supposed to work ? Should there be two comments ?
> 
> 

Multiple comments isn't preferred. If we can edit the single comment it would look better. For issues similarity we can also consider editing the specification and adding a footer regarding similarities. 

> 
> Also, `Another configuration of this idea could be to recommend the contributor in the organization with the highest match, even if it doesn't hit the threshold`. So the 75% threshold is only for task similarity ?

This can be handled in a separate task

**Comment by sshivaditya2019** [comment]
I attempted to address a few issues, but I’m wondering if the kernel supports `issues.label_added`. I’m not receiving messages from the webhook; while the webhook is invoked, it seems the kernel isn’t processing them.

Currently, when an issue is assigned, the payload doesn’t update. Is there another plugin that handles this update? If I add webhook support for `issues.created` and `issues.updated`, it might increase coupling. The intention was to keep the `generate-vector-embeddings` plugin standalone. Should this functionality be integrated into the `generate-vector-plugin`, or should it be a separate plugin? Just to clarify, the assignment feature doesn’t require embeddings.

**Comment by 0x4007** [comment]
> I attempted to address a few issues, but I’m wondering if the kernel supports `issues.label_added`. I’m not receiving messages from the webhook; while the webhook is invoked, it seems the kernel isn’t processing them.

`issues.label_added` is certainly supported. That is how our pricing is set based on the `priority` and `time` labels.

> 
> Currently, when an issue is assigned, the payload doesn’t update. Is there another plugin that handles this update? If I add webhook support for `issues.created` and `issues.updated`, it might increase coupling. The intention was to keep the `generate-vector-embeddings` plugin standalone. Should this functionality be integrated into the `generate-vector-plugin`, or should it be a separate plugin? Just to clarify, the assignment feature doesn’t require embeddings.

We do want to decrease coupling but at this point I am leaning towards stacking tech debt so that we can ship more capabilities faster. We had quite a lull in the last couple of months and I want to speed things along. So do what you think is faster to ship and we can clean tech debt later.

**Comment by gentlementlegen** [comment]
When multiple plugins are specified under a `uses` key, they will run sequentially and send their output to the following plugin.

**Comment by 0x4007** [comment]
> I’m not receiving messages from the webhook; while the webhook is invoked, it seems the kernel isn’t processing them.

Are you using your own GitHub App? Have you correctly set the permissions? If you are using our kernel, the GitHub App definitely monitors labels.

**Comment by sshivaditya2019** [comment]
> > I’m not receiving messages from the webhook; while the webhook is invoked, it seems the kernel isn’t processing them.
> 
> Are you using your own GitHub App? Have you correctly set the permissions? If you are using our kernel, the official instance, it definitely relays label events.

I fixed that, it was `issues.labled`, I was using something else.
